### ISSUE TITLE
Build im Master schlägt fehl wg. fehlendem Paket

### ISSUE THREAD

**Issue by miraKlein** [INWT/INWTUtils#10]
Nach dem Merge von #8 in den Master schlägt der Build im Master fehl (https://inwt-vmeh2.inwt.de/jenkins/job/INWTUtils/job/master/1/console). Anscheinend muss `readr` noch installiert werden. @aneudecker Hast du die entsprechenden Rechte?

**Comment by aneudecker** [comment]
Ist gefixt. Da readr nur im INWTUtils Dock Image vorhanden ist, muss man auch dieses Image verwenden um das Paket zu bauen. Das wird jetzt gemacht und läuft durch.
