### ISSUE TITLE
create wird nicht mehr von devtools exportiert

### ISSUE THREAD

**Issue by aneudecker** [INWT/INWTUtils#7]
Bei der Installation von INWTUtils mit einer neuen Version von devtools kommt die folgende Fehlermeldung:

```
Error: object ‘create’ is not exported by 'namespace:devtools'
```

Siehe auch den Vergleich der Version 2.0.1 und 2.1.0 https://github.com/r-lib/devtools/compare/v2.0.1...master#diff-7347fe5a0f184f79ef064e92e3beb297L29

Im Zug von https://github.com/INWT/IT-Leitfaden/issues/963 müssen wir dieses Problem noch beheben.

**Comment by miraKlein** [comment]
Die entsprechenden Funktionen sind jetzt höchstwahrscheinlich im Paket `usethis` zu finden.

**Comment by miraKlein** [comment]
Die Funktionen (`create`/`setup`, `use_testthat`) können nicht eins zu eins durch ihre Äquivalente aus `usethis` ersetzt werden, weil `usethis` gewisse Anforderung an das (Nicht)vorhandensein eines RStudio-Projekts und die gesamte Dateistruktur hat. Es soll kein Paket genested in einem Projekt erstellt werden.
Bisher wurde alles in einem temporären Ordner erstellt und dann ins Zielverzeichnis verschoben, weil sonst `devtools` gemeckert hat. Den Workaround kann man sich jetzt sparen, aber es sind halt andere Probleme zu lösen, z.B. indem zwischenzeitlich das Working Directory geändert und mittels `on.exit()` wieder zurück gesetzt wird. Dies scheint leider die beste Variante zu sein.
